package parser

enum class NodeType {
    Program,
    Block,
    VariableDeclaration,
    Identifier,
    BinaryExpression,
    AssignmentExpression,
    MemberExpression,
    CallExpression,
    NumericLiteral,
    StringLiteral,
    Object,
    Property,
    EmptyStatement,
    VariableStatement,
    IfStatement,
    UnlessStatement,
    BooleanLiteral,
    NullLiteral,
    LogicalExpression,
    UnaryExpression,
    WhileStatement,
    DoWhileStatement,
    ForStatement,
    FunctionDeclaration,
    ReturnStatement,
    TypeDefinition,
    TypePropertyDefinition,
    TypeAnnotation,
    FunctionParameter,
    ArrayLiteral,
    FunctionExpression,
    BreakStatement,
    ImportStatement,
    TryCatch
}